import { useState, useMemo } from 'react'
import { Navigate } from 'react-router-dom'
import AdminLayout from '../../components/admin/AdminLayout'
import { useAuth } from '../../contexts/AuthContext'
import { buildOutcomeEngineAlertSummary } from '../../domain/adminAutomation'
import { loadSharedDealLifecycleRecords } from '../../domain/dealLifecycle'

type IncidentSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info'
type IncidentStatus = 'open' | 'investigating' | 'contained' | 'resolved' | 'closed'
type AuditStatus = 'completed' | 'in_progress' | 'scheduled' | 'failed'

type SecurityIncident = {
    id: string
    title: string
    type: 'unauthorized_access' | 'data_breach' | 'policy_violation' | 'anomaly' | 'malware' | 'insider_threat'
    severity: IncidentSeverity
    status: IncidentStatus
    source: string
    affectedUsers: number
    autoDetected: boolean
    createdAt: string
    assignee: string
    autoAction: string
}

type AuditLog = {
    id: string
    action: string
    actor: string
    target: string
    ipAddress: string
    timestamp: string
    risk: 'low' | 'medium' | 'high'
    autoFlagged: boolean
}

type ComplianceReport = {
    id: string
    name: string
    type: 'soc2' | 'hipaa' | 'gdpr' | 'fedramp' | 'custom'
    status: AuditStatus
    lastRun: string
    nextRun: string
    autoGenerated: boolean
    findings: number
}

type AutomationRule = {
    id: string
    name: string
    description: string
    enabled: boolean
    trigger: string
    action: string
    lastRun: string
    type: 'incident_detection' | 'auto_response' | 'audit' | 'compliance' | 'threat_intel'
}

type ScheduledTask = {
    id: string
    name: string
    type: 'log_archive' | 'report_generation' | 'vulnerability_scan' | 'backup' | 'access_review'
    schedule: string
    status: 'active' | 'paused' | 'failed'
    lastRun: string
    nextRun: string
    autoExecuted: boolean
}

const mockIncidents: SecurityIncident[] = [
    { id: 'inc-001', title: 'Multiple failed login attempts from unknown IP', type: 'unauthorized_access', severity: 'high', status: 'investigating', source: 'Auto-detect (ML)', affectedUsers: 1, autoDetected: true, createdAt: '2 hours ago', assignee: 'admin_001', autoAction: 'IP blocked + MFA forced' },
    { id: 'inc-002', title: 'Unusual data export volume detected', type: 'anomaly', severity: 'medium', status: 'open', source: 'Behavioral analytics', affectedUsers: 1, autoDetected: true, createdAt: '5 hours ago', assignee: 'Unassigned', autoAction: 'Export paused pending review' },
    { id: 'inc-003', title: 'Service account key rotation overdue', type: 'policy_violation', severity: 'low', status: 'contained', source: 'Policy scanner', affectedUsers: 0, autoDetected: true, createdAt: '1 day ago', assignee: 'admin_002', autoAction: 'Alert sent to SecOps' },
    { id: 'inc-004', title: 'Potential insider threat - bulk download', type: 'insider_threat', severity: 'critical', status: 'investigating', source: 'DLP Alert', affectedUsers: 3, autoDetected: true, createdAt: '3 hours ago', assignee: 'admin_001', autoAction: 'Access suspended + flagged' },
    { id: 'inc-005', title: 'Expired SSL certificate on API endpoint', type: 'policy_violation', severity: 'medium', status: 'resolved', source: 'Cert monitor', affectedUsers: 0, autoDetected: true, createdAt: '2 days ago', assignee: 'admin_003', autoAction: 'Auto-renewed' },
    { id: 'inc-006', title: 'New admin account created', type: 'policy_violation', severity: 'info', status: 'open', source: 'Audit log', affectedUsers: 1, autoDetected: false, createdAt: '6 hours ago', assignee: 'Unassigned', autoAction: 'Pending approval' },
]

const mockAuditLogs: AuditLog[] = [
    { id: 'log-001', action: 'USER_LOGIN', actor: 'sarah.chen@healthco.io', target: 'Dashboard', ipAddress: '192.168.1.45', timestamp: '2 min ago', risk: 'low', autoFlagged: false },
    { id: 'log-002', action: 'DATASET_DOWNLOAD', actor: 'mjohnson@finvault.com', target: 'Clinical Outcomes Delta', ipAddress: '10.0.2.55', timestamp: '15 min ago', risk: 'medium', autoFlagged: true },
    { id: 'log-003', action: 'ROLE_CHANGE', actor: 'admin_001', target: 'part_anon_089', ipAddress: '192.168.1.10', timestamp: '1 hour ago', risk: 'high', autoFlagged: true },
    { id: 'log-004', action: 'API_KEY_CREATED', actor: 'aisha.p@fintech.io', target: 'API Access', ipAddress: '172.16.3.22', timestamp: '3 hours ago', risk: 'medium', autoFlagged: true },
    { id: 'log-005', action: 'BULK_EXPORT', actor: 'lisa.t@bank.com', target: 'Market Data Q4', ipAddress: '10.0.1.88', timestamp: '5 hours ago', risk: 'high', autoFlagged: true },
    { id: 'log-006', action: 'USER_LOGIN_FAILED', actor: 'unknown', target: 'Admin Console', ipAddress: '45.33.22.11', timestamp: '6 hours ago', risk: 'high', autoFlagged: true },
    { id: 'log-007', action: 'TRUST_SCORE_UPDATE', actor: 'system', target: 'MedData Solutions', ipAddress: 'internal', timestamp: '1 day ago', risk: 'low', autoFlagged: false },
]

const mockComplianceReports: ComplianceReport[] = [
    { id: 'rep-001', name: 'SOC 2 Type II Quarterly', type: 'soc2', status: 'completed', lastRun: '2026-03-15', nextRun: '2026-06-15', autoGenerated: true, findings: 2 },
    { id: 'rep-002', name: 'HIPAA Access Audit', type: 'hipaa', status: 'scheduled', lastRun: '2026-03-01', nextRun: '2026-04-01', autoGenerated: true, findings: 0 },
    { id: 'rep-003', name: 'GDPR Data Subject Request', type: 'gdpr', status: 'in_progress', lastRun: 'Never', nextRun: 'On-demand', autoGenerated: false, findings: 0 },
    { id: 'rep-004', name: 'FedRAMP Continuous Monitoring', type: 'fedramp', status: 'completed', lastRun: '2026-03-20', nextRun: '2026-03-27', autoGenerated: true, findings: 1 },
    { id: 'rep-005', name: 'Monthly Security Controls', type: 'custom', status: 'completed', lastRun: '2026-03-10', nextRun: '2026-04-10', autoGenerated: true, findings: 3 },
]

const automationRules: AutomationRule[] = [
    { id: 'ar-1', name: 'Anomaly Detection', description: 'Detect unusual patterns in user behavior using ML', enabled: true, trigger: 'Real-time behavior analysis', action: 'Alert + auto-contain', lastRun: 'Real-time', type: 'incident_detection' },
    { id: 'ar-2', name: 'Auto-Incident Triage', description: 'Automatically classify and prioritize security incidents', enabled: true, trigger: 'New incident detected', action: 'Classify + assign', lastRun: '5 min ago', type: 'incident_detection' },
    { id: 'ar-3', name: 'IP Block Automation', description: 'Auto-block IPs with failed login threshold', enabled: true, trigger: '10+ failed attempts', action: 'Block IP + notify', lastRun: '2 hours ago', type: 'auto_response' },
    { id: 'ar-4', name: 'Audit Log Archival', description: 'Move logs to cold storage after 90 days', enabled: true, trigger: 'Daily at 2:00 AM', action: 'Archive to S3', lastRun: 'Yesterday 2:00 AM', type: 'audit' },
    { id: 'ar-5', name: 'Compliance Report Generation', description: 'Auto-generate compliance reports on schedule', enabled: true, trigger: 'Scheduled (monthly/quarterly)', action: 'Generate + notify', lastRun: '3 days ago', type: 'compliance' },
    { id: 'ar-6', name: 'Threat Intelligence Feed', description: 'Query threat intel sources for known bad actors', enabled: false, trigger: 'Hourly', action: 'Update blocklist', lastRun: 'Never', type: 'threat_intel' },
    { id: 'ar-7', name: 'MFA Enforcement', description: 'Force MFA on accounts with suspicious activity', enabled: true, trigger: 'Risk score > 70', action: 'Force MFA reset', lastRun: '1 day ago', type: 'auto_response' },
    { id: 'ar-8', name: 'DLP Alert Automation', description: 'Auto-quarantine data transfers flagged by DLP', enabled: true, trigger: 'DLP rule triggered', action: 'Quarantine + alert', lastRun: '6 hours ago', type: 'auto_response' },
]

const scheduledTasks: ScheduledTask[] = [
    { id: 'st-001', name: 'Archive audit logs (90+ days)', type: 'log_archive', schedule: 'Daily 2:00 AM', status: 'active', lastRun: 'Yesterday 2:00 AM', nextRun: 'Tomorrow 2:00 AM', autoExecuted: true },
    { id: 'st-002', name: 'SOC 2 compliance report', type: 'report_generation', schedule: 'Quarterly', status: 'active', lastRun: '2026-03-15', nextRun: '2026-06-15', autoExecuted: true },
    { id: 'st-003', name: 'HIPAA access audit', type: 'report_generation', schedule: 'Monthly', status: 'active', lastRun: '2026-03-01', nextRun: '2026-04-01', autoExecuted: true },
    { id: 'st-004', name: 'Vulnerability scan', type: 'vulnerability_scan', schedule: 'Weekly', status: 'active', lastRun: '2026-03-20', nextRun: '2026-03-27', autoExecuted: true },
    { id: 'st-005', name: 'Database backup', type: 'backup', schedule: 'Daily 3:00 AM', status: 'active', lastRun: 'Today 3:00 AM', nextRun: 'Tomorrow 3:00 AM', autoExecuted: true },
    { id: 'st-006', name: 'Access review reminder', type: 'access_review', schedule: 'Quarterly', status: 'paused', lastRun: '2026-01-15', nextRun: 'Paused', autoExecuted: true },
]

const severityClasses: Record<IncidentSeverity, string> = {
    critical: 'text-rose-300 bg-rose-500/20 border-rose-500/40',
    high: 'text-orange-300 bg-orange-500/20 border-orange-500/40',
    medium: 'text-amber-300 bg-amber-500/20 border-amber-500/40',
    low: 'text-blue-300 bg-blue-500/20 border-blue-500/40',
    info: 'text-slate-300 bg-slate-500/20 border-slate-500/40'
}

const statusClasses: Record<IncidentStatus, string> = {
    open: 'text-rose-300 bg-rose-500/10',
    investigating: 'text-amber-300 bg-amber-500/10',
    contained: 'text-blue-300 bg-blue-500/10',
    resolved: 'text-emerald-300 bg-emerald-500/10',
    closed: 'text-slate-400 bg-slate-500/10'
}

const riskClasses: Record<string, string> = {
    low: 'text-emerald-300',
    medium: 'text-amber-300',
    high: 'text-rose-300'
}

const reportStatusClasses: Record<AuditStatus, string> = {
    completed: 'text-emerald-300 bg-emerald-500/10',
    in_progress: 'text-amber-300 bg-amber-500/10',
    scheduled: 'text-blue-300 bg-blue-500/10',
    failed: 'text-rose-300 bg-rose-500/10'
}

export default function SecurityCompliancePage({ title = 'Security & Compliance', subtitle = 'Automated security monitoring, incident response & compliance reporting' }: { title?: string, subtitle?: string }) {
    const auth = useAuth()
    const [activeTab, setActiveTab] = useState<'incidents' | 'outcome-engine' | 'audit-logs' | 'automation' | 'compliance' | 'scheduled'>('incidents')
    const [rules, setRules] = useState<AutomationRule[]>(automationRules)

    if (!auth.isAuthenticated) {
        return <Navigate to="/admin/login" replace />
    }

    const toggleRule = (ruleId: string) => {
        setRules(prev => prev.map(rule => 
            rule.id === ruleId ? { ...rule, enabled: !rule.enabled } : rule
        ))
    }

    const outcomeEngineSummary = useMemo(
        () => buildOutcomeEngineAlertSummary(loadSharedDealLifecycleRecords()),
        []
    )

    const stats = useMemo(() => ({
        openIncidents: mockIncidents.filter(i => i.status === 'open' || i.status === 'investigating').length,
        criticalIncidents: mockIncidents.filter(i => i.severity === 'critical').length,
        autoDetected: mockIncidents.filter(i => i.autoDetected).length,
        flaggedLogs: mockAuditLogs.filter(l => l.autoFlagged).length,
        autoGeneratedReports: mockComplianceReports.filter(r => r.autoGenerated).length,
        activeTasks: scheduledTasks.filter(t => t.status === 'active').length,
        outcomeGroups: outcomeEngineSummary.totalFailureGroups
    }), [outcomeEngineSummary.totalFailureGroups])

    const tabs = [
        { id: 'incidents', label: 'Incidents', count: stats.openIncidents },
        { id: 'outcome-engine', label: 'Outcome Engine', count: stats.outcomeGroups },
        { id: 'audit-logs', label: 'Audit Logs', count: mockAuditLogs.length },
        { id: 'automation', label: 'Automation Rules', count: rules.filter(r => r.enabled).length },
        { id: 'compliance', label: 'Compliance Reports', count: mockComplianceReports.length },
        { id: 'scheduled', label: 'Scheduled Tasks', count: stats.activeTasks }
    ]

    return (
        <AdminLayout title={title} subtitle={subtitle}>
            <div className="relative min-h-screen text-white">
                <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_15%_15%,rgba(16,185,129,0.14),transparent_40%),radial-gradient(circle_at_80%_10%,rgba(59,130,246,0.14),transparent_35%),radial-gradient(circle_at_40%_80%,rgba(251,191,36,0.08),transparent_35%)]" />
                <div className="relative mx-auto max-w-7xl px-6 py-10 lg:px-10">
                    <header className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
                        <div>
                            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">
                                Administration
                            </div>
                            <h1 className="mt-4 text-4xl font-bold tracking-tight text-white sm:text-5xl">Security & Compliance</h1>
                            <p className="mt-2 max-w-2xl text-slate-400">
                                Automated security monitoring, incident detection, incident response, and compliance reporting.
                            </p>
                        </div>
                        <div className="flex gap-3">
                            <button className="rounded-xl border border-rose-400/60 bg-rose-500/10 px-4 py-2 text-sm font-semibold text-rose-100 shadow-[0_10px_30px_rgba(244,63,94,0.22)] hover:bg-rose-500/20 transition">
                                Report Incident
                            </button>
                            <button className="rounded-xl border border-cyan-400/60 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-100 shadow-[0_10px_30px_rgba(34,211,238,0.22)] hover:bg-cyan-500/20 transition">
                                Generate Report
                            </button>
                        </div>
                    </header>

                    <div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-6">
                        <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4">
                            <p className="text-xs uppercase tracking-[0.14em] text-rose-400">Open Incidents</p>
                            <p className="mt-2 text-3xl font-bold text-rose-100">{stats.openIncidents}</p>
                        </div>
                        <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4">
                            <p className="text-xs uppercase tracking-[0.14em] text-rose-400">Critical</p>
                            <p className="mt-2 text-3xl font-bold text-rose-100">{stats.criticalIncidents}</p>
                        </div>
                        <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4">
                            <p className="text-xs uppercase tracking-[0.14em] text-emerald-400">Auto-Detected</p>
                            <p className="mt-2 text-3xl font-bold text-emerald-100">{stats.autoDetected}</p>
                        </div>
                        <div className="rounded-xl border border-blue-500/30 bg-blue-500/10 p-4">
                            <p className="text-xs uppercase tracking-[0.14em] text-blue-400">Flagged Logs</p>
                            <p className="mt-2 text-3xl font-bold text-blue-100">{stats.flaggedLogs}</p>
                        </div>
                        <div className="rounded-xl border border-purple-500/30 bg-purple-500/10 p-4">
                            <p className="text-xs uppercase tracking-[0.14em] text-purple-400">Auto Reports</p>
                            <p className="mt-2 text-3xl font-bold text-purple-100">{stats.autoGeneratedReports}</p>
                        </div>
                        <div className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-4">
                            <p className="text-xs uppercase tracking-[0.14em] text-cyan-400">Outcome Alerts</p>
                            <p className="mt-2 text-3xl font-bold text-cyan-100">{stats.outcomeGroups}</p>
                        </div>
                    </div>

                    <div className="mt-8 flex gap-1 overflow-x-auto rounded-xl border border-white/10 bg-white/5 p-1">
                        {tabs.map(tab => (
                            <button
                                key={tab.id}
                                onClick={() => setActiveTab(tab.id as typeof activeTab)}
                                className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition ${
                                    activeTab === tab.id 
                                        ? 'bg-cyan-500/20 text-cyan-100' 
                                        : 'text-slate-400 hover:text-white'
                                }`}
                            >
                                {tab.label}
                                <span className={`rounded-full px-2 py-0.5 text-xs ${
                                    activeTab === tab.id ? 'bg-cyan-500/40' : 'bg-white/10'
                                }`}>
                                    {tab.count}
                                </span>
                            </button>
                        ))}
                    </div>

                    {activeTab === 'incidents' && (
                        <section className="mt-6">
                            <div className="flex items-center justify-between gap-3 mb-4">
                                <div className="flex items-center gap-3">
                                    <input 
                                        type="text" 
                                        placeholder="Search incidents..." 
                                        className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white placeholder-slate-500 focus:border-cyan-400 focus:outline-none w-64"
                                    />
                                    <select className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white focus:border-cyan-400 focus:outline-none">
                                        <option>All Severities</option>
                                        <option>Critical</option>
                                        <option>High</option>
                                        <option>Medium</option>
                                        <option>Low</option>
                                    </select>
                                    <select className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white focus:border-cyan-400 focus:outline-none">
                                        <option>All Status</option>
                                        <option>Open</option>
                                        <option>Investigating</option>
                                        <option>Contained</option>
                                        <option>Resolved</option>
                                    </select>
                                </div>
                            </div>
                            <div className="space-y-3">
                                {mockIncidents.map(incident => (
                                    <article 
                                        key={incident.id}
                                        className="relative overflow-hidden rounded-xl border border-white/10 bg-[#0a1424] p-5 shadow-[0_12px_40px_rgba(0,0,0,0.28)]"
                                    >
                                        <div className="absolute inset-0 opacity-5 bg-gradient-to-r from-rose-500 to-transparent" />
                                        <div className="relative flex items-start justify-between gap-4">
                                            <div className="flex items-start gap-4">
                                                <div className={`mt-1 h-3 w-3 rounded-full ${
                                                    incident.severity === 'critical' ? 'bg-rose-500 animate-pulse' :
                                                    incident.severity === 'high' ? 'bg-orange-500' :
                                                    incident.severity === 'medium' ? 'bg-amber-500' : 'bg-blue-500'
                                                }`} />
                                                <div>
                                                    <div className="flex items-center gap-2 flex-wrap">
                                                        <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold ${severityClasses[incident.severity]}`}>
                                                            {incident.severity}
                                                        </span>
                                                        <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-semibold ${statusClasses[incident.status]}`}>
                                                            {incident.status}
                                                        </span>
                                                        {incident.autoDetected && (
                                                            <span className="inline-flex items-center gap-1 text-xs text-cyan-400">
                                                                <span className="h-1.5 w-1.5 rounded-full bg-cyan-400" /> Auto-detected
                                                            </span>
                                                        )}
                                                    </div>
                                                    <h3 className="mt-2 text-base font-semibold text-white">{incident.title}</h3>
                                                    <div className="mt-2 flex items-center gap-4 text-xs text-slate-500">
                                                        <span>Type: {incident.type.replace('_', ' ')}</span>
                                                        <span>Source: {incident.source}</span>
                                                        <span>Affected: {incident.affectedUsers} user(s)</span>
                                                        <span>Created: {incident.createdAt}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="text-right">
                                                <p className="text-xs text-slate-500">Auto-Action</p>
                                                <p className="text-sm text-amber-300">{incident.autoAction}</p>
                                                <div className="mt-2">
                                                    {incident.assignee !== 'Unassigned' ? (
                                                        <span className="text-xs text-slate-400">Assigned to: {incident.assignee}</span>
                                                    ) : (
                                                        <button className="rounded-lg border border-cyan-400/40 bg-cyan-500/10 px-3 py-1 text-xs font-semibold text-cyan-100 hover:bg-cyan-500/20">
                                                            Assign
                                                        </button>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                    </article>
                                ))}
                            </div>
                        </section>
                    )}

                    {activeTab === 'outcome-engine' && (
                        <section className="mt-6 space-y-6">
                            <div className="grid gap-4 md:grid-cols-4">
                                <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4">
                                    <p className="text-xs uppercase tracking-[0.14em] text-rose-400">Failure Groups</p>
                                    <p className="mt-2 text-3xl font-bold text-rose-100">{outcomeEngineSummary.totalFailureGroups}</p>
                                </div>
                                <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4">
                                    <p className="text-xs uppercase tracking-[0.14em] text-amber-400">Frozen Deals</p>
                                    <p className="mt-2 text-3xl font-bold text-amber-100">{outcomeEngineSummary.frozenDealCount}</p>
                                </div>
                                <div className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-4">
                                    <p className="text-xs uppercase tracking-[0.14em] text-cyan-400">Repeat Offenders</p>
                                    <p className="mt-2 text-3xl font-bold text-cyan-100">{outcomeEngineSummary.repeatOffenderCount}</p>
                                </div>
                                <div className="rounded-xl border border-blue-500/30 bg-blue-500/10 p-4">
                                    <p className="text-xs uppercase tracking-[0.14em] text-blue-400">False-Positive Candidates</p>
                                    <p className="mt-2 text-3xl font-bold text-blue-100">{outcomeEngineSummary.falsePositiveCandidateCount}</p>
                                </div>
                            </div>

                            <div className="grid gap-4">
                                {outcomeEngineSummary.groups.map(group => (
                                    <article
                                        key={group.id}
                                        className="relative overflow-hidden rounded-xl border border-white/10 bg-[#0a1424] p-5 shadow-[0_12px_40px_rgba(0,0,0,0.28)]"
                                    >
                                        <div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_80%_20%,rgba(34,211,238,0.15),transparent_45%)]" />
                                        <div className="relative flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
                                            <div className="space-y-3">
                                                <div className="flex flex-wrap items-center gap-2">
                                                    <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold uppercase ${
                                                        group.severity === 'critical'
                                                            ? 'border-rose-500/40 text-rose-300'
                                                            : group.severity === 'high'
                                                                ? 'border-amber-500/40 text-amber-300'
                                                                : 'border-cyan-500/40 text-cyan-300'
                                                    }`}>
                                                        {group.severity}
                                                    </span>
                                                    {group.repeatOffender && (
                                                        <span className="inline-flex items-center rounded-full border border-rose-500/40 px-2.5 py-1 text-[11px] font-semibold uppercase text-rose-300">
                                                            Repeat offender
                                                        </span>
                                                    )}
                                                    {group.falsePositiveCandidate && (
                                                        <span className="inline-flex items-center rounded-full border border-blue-500/40 px-2.5 py-1 text-[11px] font-semibold uppercase text-blue-300">
                                                            Threshold review
                                                        </span>
                                                    )}
                                                </div>
                                                <div>
                                                    <h3 className="text-lg font-semibold text-white">{group.dataset}</h3>
                                                    <p className="mt-1 text-sm text-slate-400">{group.provider}</p>
                                                </div>
                                                <p className="max-w-3xl text-sm text-slate-300">{group.summary}</p>
                                                <div className="flex flex-wrap gap-4 text-xs text-slate-500">
                                                    <span>{group.failureCount} grouped failure(s)</span>
                                                    <span>{group.frozenDeals} frozen deal(s)</span>
                                                </div>
                                            </div>
                                            <div className="min-w-[240px] rounded-xl border border-white/10 bg-white/5 p-4">
                                                <p className="text-xs uppercase tracking-[0.14em] text-slate-500">Recommended Action</p>
                                                <p className="mt-2 text-sm text-cyan-100">{group.recommendedAction}</p>
                                            </div>
                                        </div>
                                        <div className="relative mt-4 grid gap-2">
                                            {group.findings.map(finding => (
                                                <div key={finding} className="rounded-lg border border-slate-800/70 bg-slate-950/45 px-3 py-2 text-sm text-slate-300">
                                                    {finding}
                                                </div>
                                            ))}
                                        </div>
                                    </article>
                                ))}
                                {outcomeEngineSummary.groups.length === 0 && (
                                    <div className="rounded-xl border border-white/10 bg-[#0a1424] px-5 py-10 text-center text-sm text-slate-400">
                                        No grouped outcome-engine alerts are active right now.
                                    </div>
                                )}
                            </div>
                        </section>
                    )}

                    {activeTab === 'audit-logs' && (
                        <section className="mt-6">
                            <div className="flex items-center justify-between gap-3 mb-4">
                                <div className="flex items-center gap-3">
                                    <input 
                                        type="text" 
                                        placeholder="Search logs..." 
                                        className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white placeholder-slate-500 focus:border-cyan-400 focus:outline-none w-64"
                                    />
                                    <select className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white focus:border-cyan-400 focus:outline-none">
                                        <option>All Actions</option>
                                        <option>USER_LOGIN</option>
                                        <option>DATASET_DOWNLOAD</option>
                                        <option>ROLE_CHANGE</option>
                                        <option>BULK_EXPORT</option>
                                    </select>
                                    <select className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white focus:border-cyan-400 focus:outline-none">
                                        <option>All Risk Levels</option>
                                        <option>High</option>
                                        <option>Medium</option>
                                        <option>Low</option>
                                    </select>
                                </div>
                                <button className="rounded-lg border border-white/20 bg-white/5 px-3 py-2 text-xs font-semibold text-white hover:bg-white/10 transition">
                                    Export Logs
                                </button>
                            </div>
                            <div className="overflow-hidden rounded-xl border border-white/10 bg-[#0a1424]">
                                <table className="w-full text-sm">
                                    <thead className="bg-white/5 text-xs uppercase tracking-[0.12em] text-slate-400">
                                        <tr>
                                            <th className="px-4 py-3 text-left">Timestamp</th>
                                            <th className="px-4 py-3 text-left">Action</th>
                                            <th className="px-4 py-3 text-left">Actor</th>
                                            <th className="px-4 py-3 text-left">Target</th>
                                            <th className="px-4 py-3 text-left">IP Address</th>
                                            <th className="px-4 py-3 text-left">Risk</th>
                                            <th className="px-4 py-3 text-left">Flagged</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-800/70">
                                        {mockAuditLogs.map(log => (
                                            <tr key={log.id} className="hover:bg-white/5 transition-colors">
                                                <td className="px-4 py-3 text-slate-400 font-mono text-xs">{log.timestamp}</td>
                                                <td className="px-4 py-3 text-white font-medium">{log.action}</td>
                                                <td className="px-4 py-3 text-slate-200">{log.actor}</td>
                                                <td className="px-4 py-3 text-slate-300">{log.target}</td>
                                                <td className="px-4 py-3 text-slate-400 font-mono text-xs">{log.ipAddress}</td>
                                                <td className="px-4 py-3">
                                                    <span className={`font-semibold ${riskClasses[log.risk]}`}>
                                                        {log.risk.toUpperCase()}
                                                    </span>
                                                </td>
                                                <td className="px-4 py-3">
                                                    {log.autoFlagged ? (
                                                        <span className="inline-flex items-center gap-1 text-xs text-rose-400">
                                                            <span className="h-1.5 w-1.5 rounded-full bg-rose-400" /> Auto-flagged
                                                        </span>
                                                    ) : (
                                                        <span className="text-slate-600">-</span>
                                                    )}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </section>
                    )}

                    {activeTab === 'automation' && (
                        <section className="mt-6">
                            <div className="flex items-center justify-between gap-3 mb-4">
                                <h2 className="text-lg font-semibold text-white">Automation Rules</h2>
                                <button className="rounded-lg border border-white/20 bg-white/5 px-3 py-2 text-xs font-semibold text-white hover:bg-white/10 transition">
                                    + Add Rule
                                </button>
                            </div>
                            <div className="grid gap-4 md:grid-cols-2">
                                {rules.map(rule => (
                                    <article 
                                        key={rule.id}
                                        className="relative overflow-hidden rounded-xl border border-white/10 bg-[#0a1424] p-5 shadow-[0_12px_40px_rgba(0,0,0,0.28)]"
                                    >
                                        <div className="absolute inset-0 opacity-30 bg-[radial-gradient(circle_at_80%_20%,rgba(244,63,94,0.15),transparent_45%)]" />
                                        <div className="relative flex items-start justify-between gap-3">
                                            <div className="flex-1">
                                                <div className="flex items-center gap-2">
                                                    <span className={`inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase ${
                                                        rule.type === 'incident_detection' ? 'border-rose-500/40 text-rose-300' :
                                                        rule.type === 'auto_response' ? 'border-orange-500/40 text-orange-300' :
                                                        rule.type === 'audit' ? 'border-blue-500/40 text-blue-300' :
                                                        rule.type === 'compliance' ? 'border-purple-500/40 text-purple-300' :
                                                        'border-amber-500/40 text-amber-300'
                                                    }`}>
                                                        {rule.type.replace('_', ' ')}
                                                    </span>
                                                </div>
                                                <h3 className="mt-2 text-base font-semibold text-white">{rule.name}</h3>
                                                <p className="mt-1 text-sm text-slate-400">{rule.description}</p>
                                            </div>
                                            <button 
                                                onClick={() => toggleRule(rule.id)}
                                                className={`relative h-6 w-11 rounded-full transition-colors ${
                                                    rule.enabled ? 'bg-emerald-500' : 'bg-slate-600'
                                                }`}
                                            >
                                                <span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition-transform ${
                                                    rule.enabled ? 'left-6' : 'left-1'
                                                }`} />
                                            </button>
                                        </div>
                                        <div className="relative mt-4 flex items-center justify-between text-xs text-slate-500">
                                            <div className="flex gap-4">
                                                <span><strong className="text-slate-400">Trigger:</strong> {rule.trigger}</span>
                                                <span><strong className="text-slate-400">Action:</strong> {rule.action}</span>
                                            </div>
                                            <span>Last run: {rule.lastRun}</span>
                                        </div>
                                    </article>
                                ))}
                            </div>
                        </section>
                    )}

                    {activeTab === 'compliance' && (
                        <section className="mt-6">
                            <div className="flex items-center justify-between gap-3 mb-4">
                                <div>
                                    <h2 className="text-lg font-semibold text-white">Compliance Reports</h2>
                                    <p className="text-sm text-slate-400">Automated compliance reporting and audit trails</p>
                                </div>
                                <button className="rounded-lg border border-white/20 bg-white/5 px-3 py-2 text-xs font-semibold text-white hover:bg-white/10 transition">
                                    + Create Report
                                </button>
                            </div>
                            <div className="overflow-hidden rounded-xl border border-white/10 bg-[#0a1424]">
                                <table className="w-full text-sm">
                                    <thead className="bg-white/5 text-xs uppercase tracking-[0.12em] text-slate-400">
                                        <tr>
                                            <th className="px-4 py-3 text-left">Report Name</th>
                                            <th className="px-4 py-3 text-left">Type</th>
                                            <th className="px-4 py-3 text-left">Status</th>
                                            <th className="px-4 py-3 text-left">Last Run</th>
                                            <th className="px-4 py-3 text-left">Next Run</th>
                                            <th className="px-4 py-3 text-left">Findings</th>
                                            <th className="px-4 py-3 text-left">Auto</th>
                                            <th className="px-4 py-3 text-right">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-800/70">
                                        {mockComplianceReports.map(report => (
                                            <tr key={report.id} className="hover:bg-white/5 transition-colors">
                                                <td className="px-4 py-3 font-medium text-white">{report.name}</td>
                                                <td className="px-4 py-3">
                                                    <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold uppercase ${
                                                        report.type === 'soc2' ? 'border-blue-500/40 text-blue-300' :
                                                        report.type === 'hipaa' ? 'border-emerald-500/40 text-emerald-300' :
                                                        report.type === 'gdpr' ? 'border-purple-500/40 text-purple-300' :
                                                        report.type === 'fedramp' ? 'border-amber-500/40 text-amber-300' :
                                                        'border-slate-500/40 text-slate-300'
                                                    }`}>
                                                        {report.type}
                                                    </span>
                                                </td>
                                                <td className="px-4 py-3">
                                                    <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-semibold ${reportStatusClasses[report.status]}`}>
                                                        {report.status.replace('_', ' ')}
                                                    </span>
                                                </td>
                                                <td className="px-4 py-3 text-slate-400">{report.lastRun}</td>
                                                <td className="px-4 py-3 text-slate-400">{report.nextRun}</td>
                                                <td className="px-4 py-3">
                                                    {report.findings > 0 ? (
                                                        <span className="inline-flex items-center rounded-full bg-rose-500/20 px-2 py-1 text-xs font-semibold text-rose-300">
                                                            {report.findings}
                                                        </span>
                                                    ) : (
                                                        <span className="text-emerald-300">0</span>
                                                    )}
                                                </td>
                                                <td className="px-4 py-3">
                                                    {report.autoGenerated ? (
                                                        <span className="inline-flex items-center gap-1 text-xs text-cyan-400">
                                                            <span className="h-1.5 w-1.5 rounded-full bg-cyan-400" /> Auto
                                                        </span>
                                                    ) : (
                                                        <span className="text-slate-500">Manual</span>
                                                    )}
                                                </td>
                                                <td className="px-4 py-3 text-right">
                                                    <button className="rounded-lg border border-slate-600 bg-slate-700/50 px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-600">
                                                        View
                                                    </button>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </section>
                    )}

                    {activeTab === 'scheduled' && (
                        <section className="mt-6">
                            <div className="flex items-center justify-between gap-3 mb-4">
                                <div>
                                    <h2 className="text-lg font-semibold text-white">Scheduled Tasks</h2>
                                    <p className="text-sm text-slate-400">Automated security operations and maintenance tasks</p>
                                </div>
                                <button className="rounded-lg border border-white/20 bg-white/5 px-3 py-2 text-xs font-semibold text-white hover:bg-white/10 transition">
                                    + Schedule Task
                                </button>
                            </div>
                            <div className="overflow-hidden rounded-xl border border-white/10 bg-[#0a1424]">
                                <table className="w-full text-sm">
                                    <thead className="bg-white/5 text-xs uppercase tracking-[0.12em] text-slate-400">
                                        <tr>
                                            <th className="px-4 py-3 text-left">Task Name</th>
                                            <th className="px-4 py-3 text-left">Type</th>
                                            <th className="px-4 py-3 text-left">Schedule</th>
                                            <th className="px-4 py-3 text-left">Status</th>
                                            <th className="px-4 py-3 text-left">Last Run</th>
                                            <th className="px-4 py-3 text-left">Next Run</th>
                                            <th className="px-4 py-3 text-left">Auto</th>
                                            <th className="px-4 py-3 text-right">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-800/70">
                                        {scheduledTasks.map(task => (
                                            <tr key={task.id} className="hover:bg-white/5 transition-colors">
                                                <td className="px-4 py-3 font-medium text-white">{task.name}</td>
                                                <td className="px-4 py-3">
                                                    <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[11px] font-semibold ${
                                                        task.type === 'log_archive' ? 'border-blue-500/40 text-blue-300' :
                                                        task.type === 'report_generation' ? 'border-purple-500/40 text-purple-300' :
                                                        task.type === 'vulnerability_scan' ? 'border-rose-500/40 text-rose-300' :
                                                        task.type === 'backup' ? 'border-emerald-500/40 text-emerald-300' :
                                                        'border-amber-500/40 text-amber-300'
                                                    }`}>
                                                        {task.type.replace('_', ' ')}
                                                    </span>
                                                </td>
                                                <td className="px-4 py-3 text-slate-400">{task.schedule}</td>
                                                <td className="px-4 py-3">
                                                    <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-semibold ${
                                                        task.status === 'active' ? 'border-emerald-500/40 text-emerald-300' :
                                                        task.status === 'paused' ? 'border-amber-500/40 text-amber-300' :
                                                        'border-rose-500/40 text-rose-300'
                                                    }`}>
                                                        <span className={`h-1.5 w-1.5 rounded-full ${
                                                            task.status === 'active' ? 'bg-emerald-400' :
                                                            task.status === 'paused' ? 'bg-amber-400' : 'bg-rose-400'
                                                        }`} />
                                                        {task.status}
                                                    </span>
                                                </td>
                                                <td className="px-4 py-3 text-slate-400">{task.lastRun}</td>
                                                <td className="px-4 py-3 text-slate-400">{task.nextRun}</td>
                                                <td className="px-4 py-3">
                                                    {task.autoExecuted ? (
                                                        <span className="inline-flex items-center gap-1 text-xs text-emerald-400">
                                                            <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /> Auto
                                                        </span>
                                                    ) : (
                                                        <span className="text-slate-500">Manual</span>
                                                    )}
                                                </td>
                                                <td className="px-4 py-3 text-right">
                                                    <div className="flex justify-end gap-2">
                                                        <button className="rounded-lg border border-slate-600 bg-slate-700/50 px-2 py-1 text-xs text-slate-300 hover:bg-slate-600">
                                                            {task.status === 'active' ? 'Pause' : 'Resume'}
                                                        </button>
                                                        <button className="rounded-lg border border-slate-600 bg-slate-700/50 px-2 py-1 text-xs text-slate-300 hover:bg-slate-600">
                                                            Run Now
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </section>
                    )}
                </div>
            </div>
        </AdminLayout>
    )
}
